cluster:
  name: "infra-logging"

client:
  replicas: 2
  heapSize: "1024m"
  resources:
    limits:
      memory: "2048Mi"
    requests:
      memory: "1024Mi"

master:
  replicas: 2
  persistence:
    storageClass: "local-storage"
  resources:
    limits:
      cpu: "1"
      memory: "1024Mi"

data:
  replicas: 3
  heapSize: "2048m"
  persistence:
    storageClass: "local-storage"
    size: "40Gi"
  resources:
    limits:
      cpu: "4"
      memory: "3072Mi"
    requests:
      memory: "2048Mi"
