apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: infra-fluent-bit
  labels:
    app: fluent-bit
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluent-bit
      annotations:
        last-modified: "1560138976"
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      serviceAccountName: infra-fluent-bit
      containers:
      - name: fluent-bit
        image: "fluent/fluent-bit:1.1.0"
        imagePullPolicy: "IfNotPresent"
        env:
          []

        resources:
          {}

        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: etcmachineid
          mountPath: /etc/machine-id
          readOnly: true
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-service.conf
          subPath: fluent-bit-service.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-input.conf
          subPath: fluent-bit-input.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-filter.conf
          subPath: fluent-bit-filter.conf
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit-output.conf
          subPath: fluent-bit-output.conf
        - name: config
          mountPath: /fluent-bit/etc/parsers_custom.conf
          subPath: parsers.conf
        - mountPath: /data1/var/lib/docker/containers
          name: dockerroot
          readOnly: true

      terminationGracePeriodSeconds: 10

      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
      - name: config
        configMap:
          name: infra-fluent-bit-config
      - hostPath:
          path: /data1/var/lib/docker/containers
        name: dockerroot

